### ISSUE TITLE
Exception when decoding a TC String generated by the encoder

### ISSUE THREAD

**Issue by pmerlet-at-didomi** [InteractiveAdvertisingBureau/iabtcf-java#125]
There is an exception when decoding a TC String generated by the encoder with a certain list of vendors.
To reproduce it, modify the list of vendors in the `setUp` of `TCStringV2EncoderTest`:

```
        encoderBuilder = TCStringEncoder.newBuilder()
            .version(2)
            .created(created)
            .lastUpdated(updated)
            .cmpId(1)
            .cmpVersion(12)
            .consentScreen(1)
            .consentLanguage("FR")
            .vendorListVersion(2)
            .tcfPolicyVersion(1)
            .isServiceSpecific(true)
            .useNonStandardStacks(false)
            .addSpecialFeatureOptIns(BitSetIntIterable.from(1, 2))
            .addPurposesConsent(BitSetIntIterable.from(4, 8))
            .addPurposesLITransparency(BitSetIntIterable.from(11, 20))
            .purposeOneTreatment(true)
            .publisherCC("DE")
            .addVendorConsent(BitSetIntIterable.from(130,
                    202,
                    184,
                    385,
                    215,
                    285,
                    343,
                    746,
                    228,
                    550,
                    69,
                    120,
                    275,
                    599,
                    368,
                    501,
                    50,
                    100,
                    301,
                    345,
                    98,
                    126,
                    574,
                    416,
                    639,
                    236,
                    512,
                    577,
                    277,
                    388,
                    185,
                    678,
                    436,
                    272,
                    769,
                    2,
                    598,
                    697,
                    199,
                    423,
                    617,
                    381,
                    153,
                    687,
                    606,
                    662,
                    311,
                    131,
                    129,
                    49,
                    469,
                    11,
                    192,
                    315,
                    681,
                    115,
                    702,
                    226,
                    707,
                    452,
                    173,
                    119,
                    193,
                    66,
                    507,
                    15,
                    77,
                    68,
                    10,
                    251,
                    16,
                    431,
                    31,
                    40,
                    164,
                    91,
                    111,
                    97,
                    793,
                    565,
                    468,
                    434,
                    12,
                    36,
                    28,
                    360,
                    791,
                    21,
                    889,
                    45,
                    162,
                    316,
                    448,
                    79,
                    82,
                    109,
                    127,
                    253,
                    39,
                    76,
                    170,
                    128,
                    144,
                    812,
                    780,
                    772,
                    506,
                    418,
                    114,
                    244,
                    361,
                    384,
                    435,
                    124,
                    71,
                    264,
                    254,
                    813,
                    27,
                    52,
                    60,
                    95,
                    278,
                    475,
                    663,
                    744,
                    671,
                    163,
                    25,
                    32,
                    42,
                    92,
                    132,
                    102,
                    142,
                    150,
                    152,
                    165,
                    284,
                    53,
                    93,
                    231,
                    234,
                    239,
                    916,
                    373,
                    830,
                    666,
                    922,
                    259,
                    573,
                    78))
            .addVendorLegitimateInterest(BitSetIntIterable.from(130,
                    202,
                    184,
                    385,
                    215,
                    285,
                    343,
                    746,
                    228,
                    550,
                    69,
                    120,
                    275,
                    599,
                    368,
                    501,
                    50,
                    100,
                    301,
                    345,
                    98,
                    126,
                    574,
                    416,
                    639,
                    236,
                    512,
                    577,
                    277,
                    388,
                    185,
                    678,
                    436,
                    272,
                    769,
                    2,
                    598,
                    697,
                    199,
                    423,
                    617,
                    381,
                    153,
                    687,
                    606,
                    662,
                    311,
                    131,
                    129,
                    49,
                    469,
                    11,
                    192,
                    315,
                    681,
                    115,
                    702,
                    226,
                    707,
                    452,
                    173,
                    119,
                    193,
                    66,
                    507,
                    15,
                    77,
                    68,
                    10,
                    251,
                    16,
                    431,
                    31,
                    40,
                    164,
                    91,
                    111,
                    97,
                    793,
                    565,
                    468,
                    434,
                    12,
                    36,
                    28,
                    360,
                    791,
                    21,
                    889,
                    45,
                    162,
                    316,
                    448,
                    79,
                    82,
                    109,
                    127,
                    253,
                    39,
                    76,
                    170,
                    128,
                    144,
                    812,
                    780,
                    772,
                    506,
                    418,
                    114,
                    244,
                    361,
                    384,
                    435,
                    124,
                    71,
                    264,
                    254,
                    813,
                    27,
                    52,
                    60,
                    95,
                    278,
                    475,
                    663,
                    744,
                    671,
                    163,
                    25,
                    32,
                    42,
                    92,
                    132,
                    102,
                    142,
                    150,
                    152,
                    165,
                    284,
                    53,
                    93,
                    231,
                    234,
                    239,
                    916,
                    373,
                    830,
                    666,
                    922,
                    259,
                    573,
                    78));
```

Then launch the tests. Several tests fail with an exception:
```
com.iabtcf.exceptions.ByteParseException: read 2 bytes at index 3717 out of bounds for buffer length 268

	at com.iabtcf.utils.BitReader.ensureReadable(BitReader.java:75)
	at com.iabtcf.utils.BitReader.readBits12(BitReader.java:225)
	at com.iabtcf.decoder.TCStringV2.fillPublisherRestrictions(TCStringV2.java:220)
	at com.iabtcf.decoder.TCStringV2.getPublisherRestrictions(TCStringV2.java:419)
	at com.iabtcf.decoder.TCStringV2.hashCode(TCStringV2.java:515)
	at com.iabtcf.decoder.TCStringDecoder.decode(TCStringDecoder.java:77)
	at com.iabtcf.decoder.TCString.decode(TCString.java:43)
	at com.iabtcf.encoder.TCStringV2EncoderTest.testEncodingUsingBuilderWithPublisherRestrictions(TCStringV2EncoderTest.java:761)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

**Comment by laktech** [comment]
I believe I've found the root cause. I'll be submitting a PR shortly.

**Comment by laktech** [comment]
@pmerlet-at-didomi are you able to verify the proposed PR by any chance?

**Comment by pmerlet-at-didomi** [comment]
Thanks, i am currently out of office but one of my colleagues should be able to look at it.

**Comment by nicolas-chaix-didomi** [comment]
@laktech the fix seems ok for us. Thanks.
